[package]
name = "gigachat"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"
tokio = { version = "1.17.0", features = ["full"] }
egui = { version = "0.17.0", features = ["persistence"] }
eframe = "0.17.0"
irc = { version = "0.15.0", features = ["default"]}
anyhow = "1.0.0"
args = "2.0.0"
env_logger = "0.7.0"
getopts = "0.2.0"
curl = "0.4.38"
serde_json = "1.0"
failure = "0.1.8"
rand = "0.8.4"
chrono = "0.4.7"
hex = "0.4.3"
image = "0.24.1"
imageproc = "0.23.0"
glob = "0.3.0"
itertools = "0.10.3"
gif = "0.11.3"
webp-animation = "0.6.0"
open = "2.1.1"
gif-dispose = "3.1.1"
regex = "1.5.5"
async-channel = "1.6.1"

[profile.release]
opt-level = 2 # fast and small wasm

[patch.crates-io]
egui = { path = "../egui/egui" }
eframe = { path = "../egui/eframe" }
weezl = { git = "https://github.com/dbckr/lzw", branch = "decode-without-starting-clear-code" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"

[profile.bench]
debug = true