[package]
name = "gigachat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.0"
tokio = { version = "1.12.0", features = ["full"] }
eframe = "0.17.0"
irc = { version = "0.15.0", features = ["default"]}
anyhow = "1.0.0"
args = "2.0.0"
env_logger = "0.7.0"
getopts = "0.2.0"
curl = "0.4.38"
serde_json = "1.0"
failure = "0.1.8"
rand = "0.8.4"
chrono = "0.4.7"

[profile.release]
opt-level = 2 # fast and small wasm

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"